### ISSUE TITLE
adding data for tests

### ISSUE THREAD

**Issue by leej3** [NIFTI-Imaging/nifti-test-data#1]
@hjmjohnson some of the data used for testing the nifti library is here: https://github.com/Washington-University/CiftiLib/tree/master/example/data

Would you prefer sub-modules for such additions or shall I just duplicate the data and reference it?

**Comment by hjmjohnson** [comment]
@leej3 Thanks for the reference to "https://github.com/Washington-University/CiftiLib".  

@afni-rickr  or @leej3 :  Can you tell me how CiftiLib codebase is related to the subdirectory: https://github.com/NIFTI-Imaging/nifti_clib/tree/master/cifti?

- [x] Should we remove the cifti directory from here?
- [x] Would the Wash-U team whant there code to replace the cifti directory here?
- [x] Are these completely different projects with different goals?

Adding this relatively small amount of data (3MB) here for convenience.  See #2.  Other solutions are possible, but they need more thought and coordination.  A good next step is to just copy the data, and we can optimize later.

Thanks.

**Comment by afni-rickr** [comment]
Hi @hjmjohnson.  Those are the exact datasets that I have been using for local nifti-2 and cifti testing, though that repo probably did not yet exist when I found them.
I have been using 2 datasets from there, Conte69.parcellations_VGD11b.32k_fs_LR.dlabel.nii and
ones.dscalar, to do NIFTI-2 I/O testing (since CIFTI is a format embedded in NIFTI-2).
Regarding cifti, there are 3 additional Conte69 datasets that I currently use for testing cifti_tool, all in that same directory.  So it might be nice to grab the 5 .nii files from there, they are under example/data.

**Comment by afni-rickr** [comment]
The CiftiLib codebase has nothing to do with what is under the cifti tree in the nifti_clib repo, they are different implementations.  Theirs is surely much more complete.

**Comment by hjmjohnson** [comment]
Thanks Rick.  I think this resolves the issue.  I'll be making a PR on nifti to start grabbing this data.

**Comment by hjmjohnson** [comment]
Data auto-downloaded as part of testing builds from nifti_clib master branch.
